# Uncomment the next line to define a global platform for your project
 platform :ios, '15.2'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'Marvelpop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyPokedex
  pod 'SwiftLint'

  target 'MarvelpopUnitTests' do
    inherit! :search_paths
    
    # Pods for testing
    pod 'SnapshotTesting', '~> 1.9.0'
    
  end
end
